CREATE TABLE IF NOT EXISTS games (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  open_time TIME NOT NULL,
  close_time TIME NOT NULL,
  open_number INTEGER,
  close_number INTEGER,
  winning_number INTEGER,
  result_number INTEGER,
  status VARCHAR(50) DEFAULT 'Active',
  minimum_bet_amount DECIMAL(10,2) DEFAULT 10,
  max_bet_amount DECIMAL(10,2) DEFAULT 1000,
  result_declared_at TIMESTAMP,
  is_active BOOLEAN DEFAULT true,
  deleted_at TIMESTAMP,
  deleted_by INTEGER,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by INTEGER,
  updated_at TIMESTAMP,
  updated_by INTEGER
);